twig_component:
    defaults:
        App\Twig\Components\: 'components/'
        
        # Custom namespace for MemoryDemo
        App\LiveMemory\Component\:
            template_directory: 'demos/live_memory/components/LiveMemory/'
            name_prefix: 'LiveMemory:'

    anonymous_template_directory: 'components/'
